### ISSUE TITLE
Support mailbox-specific limits

### ISSUE THREAD

**Issue by emersion** [emersion/go-imap-appendlimit#1]
See https://tools.ietf.org/html/rfc7889#section-3

**Comment by foxcpp** [comment]
Doesn't it requires changes in go-imap (MailboxStatus structure)? If you have any ideas on how to implement it - I can help with code.

Btw, can I somehow get value specified in APPENDLIMIT? go-imap seems to have only supported/not supported check.

**Comment by emersion** [comment]
It would be easy to add a new `imap.StatusItem` constant for `APPENDLIMIT` that could be passed to `client.Status`. Then we can just extract the value from `MailboxStatus.Items` as you said, e.g. with a new `MailboxStatusAppendLimit` function.

Adding support for _3.2.  STATUS Response to the LIST Command_ will be more involved -- we don't (yet) have `LIST-STATUS` support.

**Comment by emersion** [comment]
Ah, all of this is for client support. I just realized we don't have client support for account-specific limits (via capabilities) yet.

For server support, we can just add a function to set the `MailboxStatus.Items` field as appropriate.
